---
# Tasks for common CIS hardening

- name: Ensure system is up-to-date
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == 'Debian'

- name: Remove telnet package
  apt:
    name: telnet
    state: absent
  when: ansible_os_family == 'Debian'

- name: Set maximum password age
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: "PASS_MAX_DAYS {{ hardening_warn_password_max_days }}"
  when: ansible_os_family == 'Debian'

- name: Enforce minimum password length
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MIN_LEN'
    line: "PASS_MIN_LEN {{ hardening_min_password_length }}"
  when: ansible_os_family == 'Debian'

# --- SSH hardening: first check if sshd_config exists ---
- name: Check if SSH config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_stat

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    backup: yes
  when: sshd_config_stat.stat.exists

- name: Set SSH idle timeout
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ClientAliveInterval'
    line: "ClientAliveInterval {{ hardening_ssh_idle_timeout }}"
    backup: yes
  when: sshd_config_stat.stat.exists

- name: Disable IPv6 if requested
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "1"
    state: present
    reload: yes
  when: hardening_ipv6_disable

- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
  when: ansible_os_family == 'Debian'

- name: Configure UFW default deny incoming
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  when: ansible_os_family == 'Debian'
