name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible and yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible yamllint

      - name: Check Ansible playbook syntax
        run: |
          ansible-playbook ansible/playbook.yml --syntax-check

      - name: Run yamllint on Ansible files
        run: |
          yamllint -c .yamllint.yml ansible/
