name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python tools
        run: |
          pip install -r requirements.txt
          pip install flake8 yamllint ansible

      - name: Lint Python
        run: |
          flake8 src/

      - name: Test syntax & YAML lint
        run: |
          bash tests/test_syntax.sh

      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
